/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ContributionTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contributions"
      | "getContribution"
      | "getSharePercentage"
      | "recordContribution"
      | "totalContributions"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ContributionRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "contributions",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContribution",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSharePercentage",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalContributions",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSharePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalContributions",
    data: BytesLike
  ): Result;
}

export namespace ContributionRecordedEvent {
  export type InputTuple = [
    workspaceId: BytesLike,
    contributor: AddressLike,
    amount: BigNumberish,
    actionType: string
  ];
  export type OutputTuple = [
    workspaceId: string,
    contributor: string,
    amount: bigint,
    actionType: string
  ];
  export interface OutputObject {
    workspaceId: string;
    contributor: string;
    amount: bigint;
    actionType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContributionTracker extends BaseContract {
  connect(runner?: ContractRunner | null): ContributionTracker;
  waitForDeployment(): Promise<this>;

  interface: ContributionTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contributions: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getContribution: TypedContractMethod<
    [workspaceId: BytesLike, contributor: AddressLike],
    [bigint],
    "view"
  >;

  getSharePercentage: TypedContractMethod<
    [workspaceId: BytesLike, contributor: AddressLike],
    [bigint],
    "view"
  >;

  recordContribution: TypedContractMethod<
    [
      workspaceId: BytesLike,
      contributor: AddressLike,
      amount: BigNumberish,
      actionType: string
    ],
    [void],
    "nonpayable"
  >;

  totalContributions: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContribution"
  ): TypedContractMethod<
    [workspaceId: BytesLike, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSharePercentage"
  ): TypedContractMethod<
    [workspaceId: BytesLike, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordContribution"
  ): TypedContractMethod<
    [
      workspaceId: BytesLike,
      contributor: AddressLike,
      amount: BigNumberish,
      actionType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalContributions"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "ContributionRecorded"
  ): TypedContractEvent<
    ContributionRecordedEvent.InputTuple,
    ContributionRecordedEvent.OutputTuple,
    ContributionRecordedEvent.OutputObject
  >;

  filters: {
    "ContributionRecorded(bytes32,address,uint256,string)": TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
    ContributionRecorded: TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
  };
}
