/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ContributionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "contributions"
      | "getShareBps"
      | "totalContributions"
      | "trackContribution"
      | "workspace"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ContributionRecorded"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getShareBps",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalContributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trackContribution",
    values: [BigNumberish, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "workspace", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShareBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trackContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "workspace", data: BytesLike): Result;
}

export namespace ContributionRecordedEvent {
  export type InputTuple = [
    workspaceId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish,
    action: string
  ];
  export type OutputTuple = [
    workspaceId: bigint,
    contributor: string,
    amount: bigint,
    action: string
  ];
  export interface OutputObject {
    workspaceId: bigint;
    contributor: string;
    amount: bigint;
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Contribution extends BaseContract {
  connect(runner?: ContractRunner | null): Contribution;
  waitForDeployment(): Promise<this>;

  interface: ContributionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  contributions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getShareBps: TypedContractMethod<
    [workspaceId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;

  totalContributions: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  trackContribution: TypedContractMethod<
    [
      workspaceId: BigNumberish,
      contributor: AddressLike,
      amount: BigNumberish,
      action: string
    ],
    [void],
    "nonpayable"
  >;

  workspace: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShareBps"
  ): TypedContractMethod<
    [workspaceId: BigNumberish, contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalContributions"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "trackContribution"
  ): TypedContractMethod<
    [
      workspaceId: BigNumberish,
      contributor: AddressLike,
      amount: BigNumberish,
      action: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "workspace"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ContributionRecorded"
  ): TypedContractEvent<
    ContributionRecordedEvent.InputTuple,
    ContributionRecordedEvent.OutputTuple,
    ContributionRecordedEvent.OutputObject
  >;

  filters: {
    "ContributionRecorded(uint256,address,uint256,string)": TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
    ContributionRecorded: TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
  };
}
