/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WorkspaceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMember"
      | "createWorkspace"
      | "getMemberCount"
      | "isMember"
      | "workspaceMembers"
      | "workspaces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MemberAdded" | "WorkspaceCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [BytesLike, AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createWorkspace",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaceMembers",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaces",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "workspaceMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "workspaces", data: BytesLike): Result;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    workspaceId: BytesLike,
    member: AddressLike,
    role: string
  ];
  export type OutputTuple = [workspaceId: string, member: string, role: string];
  export interface OutputObject {
    workspaceId: string;
    member: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkspaceCreatedEvent {
  export type InputTuple = [id: BytesLike, name: string, owner: AddressLike];
  export type OutputTuple = [id: string, name: string, owner: string];
  export interface OutputObject {
    id: string;
    name: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorkspaceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WorkspaceRegistry;
  waitForDeployment(): Promise<this>;

  interface: WorkspaceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMember: TypedContractMethod<
    [
      workspaceId: BytesLike,
      member: AddressLike,
      anonymousId: BytesLike,
      role: string
    ],
    [void],
    "nonpayable"
  >;

  createWorkspace: TypedContractMethod<
    [id: BytesLike, name: string],
    [void],
    "nonpayable"
  >;

  getMemberCount: TypedContractMethod<
    [workspaceId: BytesLike],
    [bigint],
    "view"
  >;

  isMember: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  workspaceMembers: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        wallet: string;
        anonymousId: string;
        role: string;
        joinedAt: bigint;
      }
    ],
    "view"
  >;

  workspaces: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint] & {
        id: string;
        name: string;
        owner: string;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [
      workspaceId: BytesLike,
      member: AddressLike,
      anonymousId: BytesLike,
      role: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWorkspace"
  ): TypedContractMethod<[id: BytesLike, name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMemberCount"
  ): TypedContractMethod<[workspaceId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "workspaceMembers"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        wallet: string;
        anonymousId: string;
        role: string;
        joinedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "workspaces"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, boolean, bigint] & {
        id: string;
        name: string;
        owner: string;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "WorkspaceCreated"
  ): TypedContractEvent<
    WorkspaceCreatedEvent.InputTuple,
    WorkspaceCreatedEvent.OutputTuple,
    WorkspaceCreatedEvent.OutputObject
  >;

  filters: {
    "MemberAdded(bytes32,address,string)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "WorkspaceCreated(bytes32,string,address)": TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
    WorkspaceCreated: TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
  };
}
