/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Workspace {
  export type MemberStruct = {
    wallet: AddressLike;
    role: string;
    joinedAt: BigNumberish;
    active: boolean;
  };

  export type MemberStructOutput = [
    wallet: string,
    role: string,
    joinedAt: bigint,
    active: boolean
  ] & { wallet: string; role: string; joinedAt: bigint; active: boolean };
}

export interface WorkspaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMember"
      | "createWorkspace"
      | "getMembers"
      | "isMember"
      | "removeMember"
      | "updateRole"
      | "workspaces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberAdded"
      | "MemberRemoved"
      | "RoleUpdated"
      | "WorkspaceCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createWorkspace",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRole",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaces",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMembers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "workspaces", data: BytesLike): Result;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    workspaceId: BigNumberish,
    member: AddressLike,
    role: string
  ];
  export type OutputTuple = [workspaceId: bigint, member: string, role: string];
  export interface OutputObject {
    workspaceId: bigint;
    member: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [workspaceId: BigNumberish, member: AddressLike];
  export type OutputTuple = [workspaceId: bigint, member: string];
  export interface OutputObject {
    workspaceId: bigint;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleUpdatedEvent {
  export type InputTuple = [
    workspaceId: BigNumberish,
    member: AddressLike,
    newRole: string
  ];
  export type OutputTuple = [
    workspaceId: bigint,
    member: string,
    newRole: string
  ];
  export interface OutputObject {
    workspaceId: bigint;
    member: string;
    newRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkspaceCreatedEvent {
  export type InputTuple = [
    workspaceId: BigNumberish,
    name: string,
    owner: AddressLike
  ];
  export type OutputTuple = [workspaceId: bigint, name: string, owner: string];
  export interface OutputObject {
    workspaceId: bigint;
    name: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Workspace extends BaseContract {
  connect(runner?: ContractRunner | null): Workspace;
  waitForDeployment(): Promise<this>;

  interface: WorkspaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMember: TypedContractMethod<
    [workspaceId: BigNumberish, member: AddressLike, role: string],
    [void],
    "nonpayable"
  >;

  createWorkspace: TypedContractMethod<[name: string], [bigint], "nonpayable">;

  getMembers: TypedContractMethod<
    [workspaceId: BigNumberish],
    [Workspace.MemberStructOutput[]],
    "view"
  >;

  isMember: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  removeMember: TypedContractMethod<
    [workspaceId: BigNumberish, member: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRole: TypedContractMethod<
    [workspaceId: BigNumberish, member: AddressLike, newRole: string],
    [void],
    "nonpayable"
  >;

  workspaces: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean] & {
        id: bigint;
        name: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [workspaceId: BigNumberish, member: AddressLike, role: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWorkspace"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getMembers"
  ): TypedContractMethod<
    [workspaceId: BigNumberish],
    [Workspace.MemberStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [workspaceId: BigNumberish, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRole"
  ): TypedContractMethod<
    [workspaceId: BigNumberish, member: AddressLike, newRole: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "workspaces"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean] & {
        id: bigint;
        name: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RoleUpdated"
  ): TypedContractEvent<
    RoleUpdatedEvent.InputTuple,
    RoleUpdatedEvent.OutputTuple,
    RoleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WorkspaceCreated"
  ): TypedContractEvent<
    WorkspaceCreatedEvent.InputTuple,
    WorkspaceCreatedEvent.OutputTuple,
    WorkspaceCreatedEvent.OutputObject
  >;

  filters: {
    "MemberAdded(uint256,address,string)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberRemoved(uint256,address)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "RoleUpdated(uint256,address,string)": TypedContractEvent<
      RoleUpdatedEvent.InputTuple,
      RoleUpdatedEvent.OutputTuple,
      RoleUpdatedEvent.OutputObject
    >;
    RoleUpdated: TypedContractEvent<
      RoleUpdatedEvent.InputTuple,
      RoleUpdatedEvent.OutputTuple,
      RoleUpdatedEvent.OutputObject
    >;

    "WorkspaceCreated(uint256,string,address)": TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
    WorkspaceCreated: TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
  };
}
